/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
const fs = require('fs');
const path = require('path');

// Read .env.development file
const envPath = path.resolve(__dirname, '../.env.development');
const targetPath = path.resolve(__dirname, '../src/config.ts');

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) {
    console.warn(`Warning: ${filePath} does not exist. Using defaults.`);
    return {};
  }

  const content = fs.readFileSync(filePath, 'utf8');
  const env = {};

  content.split('\n').forEach((line) => {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#')) {
      const [key, ...valueParts] = trimmed.split('=');
      if (key) {
        env[key.trim()] = valueParts.join('=').trim();
      }
    }
  });

  return env;
}

const env = parseEnvFile(envPath);

const useMockApi = env.USE_MOCK_API || 'false';
const mockApiUrl = env.API_URL || '';

const environmentFileContent = `// This file is auto-generated by scripts/set-env.js
// Do not edit manually - your changes will be overwritten
export const useMockApi = ${useMockApi === 'true'};
export const mockApiUrl = '${mockApiUrl}';
`;

fs.writeFileSync(targetPath, environmentFileContent, 'utf8');
console.log(`Environment file generated at ${targetPath}`);
console.log(`  useMockApi: ${useMockApi === 'true'}`);
console.log(`  mockApiUrl: ${mockApiUrl}`);
